version: '3'
services:
  api_flyfarladies:
    build: .
    image: api_flyfarladies:latest
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "5000:5000"
    networks:
      - api-net
networks:
  api-net:
    driver: bridge
